plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Users\\36050\\Documents\\New project狗狗大赛\\website"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]